apiVersion: v1
kind: Pod
metadata:
  name: nginx-busybox-pod
  namespace: clean
  labels:
    app: nginx-busybox-pod
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80
    - name: busybox # 끊임없이 헬스체크하는 목적
      image: busybox
      # 같은 파드 내에 있기 때문에 여기서는 localhost 호출 가능하다.
      command: ['sh', '-c', 'while true; do wget -qO- http://localhost:80; sleep 5; done']