apiVersion: v1
# 자원의 종류를 명시
kind: Pod
metadata:
  name: nginx-pod # 파드의 이름을 명시
  namespace: clean-ns
  # labels는 service의 라우팅 대상이 되는 이름
  # service는 selector.app을 통해 매핑
  labels:
    app: my-nginx
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
