# 쓰면서 공부하기

# docker build 후 ecr 업로드 및 kubectl apply 시켜주기
name: deploy ordersystem with k8s
on: 
  push:
    branches:
      - practice
  jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      steps:
        - name: checkout github
          uses: actions/checkout@v2
        - name: install kubectl # 가상 컴퓨터에 kubectl 설치하기
          uses: azure/setup-kubetl@v3
          with:
            version: "v1.25.9"
          id: install
        
        - name: configure aws # aws configure
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{secrets.AWS_KEY}}
            aws-secret-access-key: ${{secrets.AWS_SECRET}}
            aws-region: ap-northeast-2

        - name: update cluster information
        